[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tech-radar-builder"
version = "0.1.0"
description = "Outil CLI pour générer et visualiser des Tech Radars à partir d'Excel et Markdown."
authors = [{ name = "Loïc Momo" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "openpyxl",
    "jinja2",
    "markdown",
    "appdirs",
    "typer>=0.9.0",
    "rich>=13.0.0",
    "watchdog>=3.0.0"
]

[project.scripts]
radar = "tech_radar_builder.cli:app"
